### ISSUE TITLE
Usage with neovim

### ISSUE THREAD

**Issue by DieracDelta** [banacorn/agda-language-server#11]
Has anyone used this with neovim? If so, can yall point me to instructions on how to set it up?

**Comment by Mechap** [comment]
Unfortunately, it appears to be not supported by the lspconfig plugin https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md

**Comment by banacorn** [comment]
Most of the functionalities of this language server relies on *custom methods*. 
So it won't work on neovim even if you have the server set up.
We're trying to replace these custom capabilities with the standard protocol as much as possible though.
