### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by cspollard** [banacorn/agda-language-server#5]
Hi,

After enabling the language server in VSCode agda-mode, I quit and restart. The language server downloads, but then the following is printed.

```
Connection Error: Client Internal Connection Error
Connection to server got closed. Server will not be restarted.
```

The debug output is

```
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicuuc.69.dylib
  Referenced from: /Users/<username>/Library/Application Support/Code/User/globalStorage/banacorn.agda-mode/v0.1.1-darwin/als
  Reason: image not found
[Error - 10:22:36 AM] Connection to server got closed. Server will not be restarted.
```

I do not have a /usr/local/opt folder (homebrew installs to /opt/homebrew). Is there a straightforward way to fix this? (btw agda-mode without LSP works just fine!)

Chris

**Comment by banacorn** [comment]
Sorry for the late response!
It appears that the executable cannot find the DLLs it needs (`libicuuc.69.dylib` and its homies)
Since you already have `homebrew`, I think this should fix it:
```
brew install icu4c
```

Also, after some tinkering, I've managed to bundle those bloody DLLs in the next release :D
